pid file = /var/run/rsyncd.pid
log file = /var/log/rsync.log
use chroot = yes
uid = perceptor
gid = perceptor

[evidence]
    path = /evidence
    comment = Perceptor evidence upload
    read only = false
    write only = true
    auth users = perceptor
    secrets file = /etc/rsyncd.secrets
    hosts allow = *
    pre-xfer exec = /opt/perceptor/deploy/rsync/rsync-pre-xfer.sh
